#!/usr/bin/env ruby
# coding: utf-8
# frozen-string-literal: true
#
# © Chris Riddoch, 2017
# This software is licensed under the GPLv3 and comes with ABSOLUTELY NO WARRANTY; for details see LICENSE in the project's main directory.

require "pry"
$: << "./lib"

require_relative "./lib/regards"

using Regards::StringRefinements::Numeric
using Regards::StringRefinements::Unhexdump

binding.pry

