= regards
Chris Riddoch <riddochc@gmail.com>
:language: ruby
:homepage: https://github.com/riddochc/regards
:revnumber: 0.0.1
:revdate: 2017-08-07

== Description

Regards are like facets - a collection of utility functions, to refine with.

Regards is a library of utility functions, in the style of the facets gem.
Being implemented as refinements, these can modify core ruby classes for the duration of the file they're used in, without causing conflicts in other code.
Become more refined by having regards, not concerns.

== Requirements

* Ruby (tested with 2.4.2)

== Installation

gem install regards

== Use

An example use:

----
# Add the number? method to the String class:
require "regards/string/to_numeric"
using Regards::StringRefinements::Numeric

# Test whether some strings are numbers
["a", "73", "*"].map {|s| s.number? } # => [false, true, false]
----

If you run +pry+ or another REPL, you may encounter an error if you try +using+ the refinement:

----
RuntimeError: main.using is permitted only at toplevel
from (pry):1:in `using'
----

Unfortunately, this is hard to work around. Placing the +using+ statement in your +~/.pryrc+ is insufficient, as is evaluating it when pry starts with the +-e+ parameter.

As YARD currently does not index refinements, documentation for each submodule of the +Regards+ module follows.

=== StringRefinements::Numeric

Refines the String class with the following methods:

number?:: Returns true if the string can be converted to a number, false otherwise. Uses to_numeric.
to_numeric:: For strings representing numbers, returns an appropriate +Integer+, +Float+, +Rational+, +Complex+, +Float::INFINITY+, +Float::-INFINITY+, +Float::NaN+ (when the string is exactly "NaN"), or +Complex+. For any other string, returns nil.

=== StringRefinements::Unhexdump

Refines the String class with the following methods:

unhexdump:: Returns a binary string based on the value of hexadecimal characters in the current string.  Ignores whitespace, returns nil on strings with any non-hexadecimal, non-whitespace characters.

=== StringRefinements::Rewrite

Refines the string class with the following methods:

rewrite:: Takes a hash of regexes for keys and callable objects as values. Creates an edited version of the string by using the callable to create a new version of the string for each matching regex.  Think of it as grouping up repeated calls to +.sub()+ into one method.

Example:

----
subs= { /foo/ => ->(m) { m.pre_match + "blah" + m.post_match },
        /bar/ => ->(m) { m.pre_match + "baz" + m.post_match } }

"one foo for a bar plz".rewrite(subs)
# => "one blah for a baz plz"
----

rewrite_all:: Continues applying +rewrite()+ to the string until the string is left unchanged by further calls to +rewrite()+.  +.rewrite()+ is to +.sub()+ as +.rewrite_all+ is to +.gsub()+. 

Note that +rewrite_all()+ can potentially loop infinitely if the edited version of the string continues to be matchable by the regexes!

Example:

----
subs = { /[aoeui]+/ => ->(m) { m.pre_match + m[0].upcase + m.post_match } }
"a test string".rewrite_all(subs)
# => "A tEst strIng"

subs = { /[aoeui]/  => ->(m) { m.pre_match + "(1)" + m.post_match },
         /[tsr]/    => ->(m) { m.pre_match + "[0]" + m.post_match } }
"a test string".rewrite_all(subs)
# => "(1) [0](1)[0][0] [0][0][0](1)ng"

subs = { /[aoeui]/  => ->(m) { m.post_match + "(1)" + m.pre_match },
         /[tsr]/    => ->(m) { m.post_match + "[0]" + m.pre_match } }
"a test string".rewrite_all(subs)
# => "[0]ng(1)[0] (1)[0](1)[0] [0][0]"
----

=== RegexpRefinements::Unroll

==== Class method: Regexp.unroll

unroll:: Construct a regular expression for matching quoted portions of a string.

Named parameters:

opening:: A regular expression matching at the beginning of the quoted portion. Defaults to /"/
closing:: A regular expression matching at the end of the quoted portion. Defaults to /"/
normal:: A regular expression identifying a non-escaped character within the string. Defaults to /[^"\\]/
special:: A regular expression for escaped characters within the string. Defaults to /\\./

The simplest way to understand this is to look at the behavior of the default "normal" with the "special" regexes, which is for identifying quoted strings.
The presence of a double-quote normally is an indication that the current point is either the beginning or the end of a quoted region.
If the region itself contains a double-quote, you need some means of indicating that it should be treated differently from normal.
The most common way of doing this is by preceding the double-quote character with a backslash.
As a consequence, a backslash can be considered the mechanism by which the following character should be treated differently from normal.

* A "normal" character is anything other than a backslash (\) or a double-quote (").
* A "special" character is a backslash followed by some other character.

The named capture 'body' in a MatchData object will contain the matched text between the 'opening' and 'closing'.

The +.unroll()+ constructor is based on a technique described in "Mastering Regular Expressions" by Jeffrey Friedl.

Example uses, in a pry session:  

----
> s = 'The reporter said, "Tell me about your work."'
> rx = Regexp.unroll()
> m = rx.match(s)
> puts m[:body]
Tell me about your work.

> s = %Q{The reporter said, "He said he's an \\"engineer\\" of some sort."}
> puts s
The reporter said, "He said he's an \"engineer\" of some sort."
> m = rx.match(s)
> puts m[:body]
He said he's an \"engineer\" of some sort.

> s = "something (one \\) two) in parentheses."
> rx = Regexp.unroll(opening: /\(/, closing: /\)/, normal: /[^\(\)\\]/)
> m = rx.match(s)
> puts m[:body]
one \) two
----

Remember that %Q{} is just another way to define a string in Ruby, and behaves similarly to ""; likewise, %q{} behaves like ''.

==== Classmethod: Regexp.unroll_and_unescape

unroll_and_unescape:: Match the quoted portion of the string and globally substitute the escaped characters (matching the 'special' regex) with the block.

This method takes the same parameters as unroll() and an additional block.

Example uses, in a pry session:

----
> s = %Q{The reporter said, "He said he's an \\"engineer\\" of some sort."}
> puts Regexp.unroll_and_unescape(s) {|c| "-#{c[-1]}-" }
He said he's an -"-engineer-"- of some sort.
> s = %Q{The reporter said, "He said he's an ""engineer"" of some sort."}
> puts Regexp.unroll_and_unescape(s, normal: /[^"]/, special: /\"\"/) {|c| "`" }
He said he's an `engineer` of some sort.
> puts Regexp.unroll_and_unescape("For the (scheme \\( fans \\) out) there", opening: /\(/, closing: /\)/, normal: /[^\(\)\\]/) {|ex| ".#{ex[-1]}." }
scheme .(. fans .). out
----

== Contributing

Please do!

You may submit a pull request at the project's github site or email patches to the maintainer.

Be courteous and professional. Criticize code, not people.

== Contributors

* Chris Riddoch

== License

Copyright © 2017 Chris Riddoch

This code is licensed under the GPLv3. See LICENSE for details.

